language: node_js
node_js:
  - 8
os: linux

install:
  - npm install -g eslint
  - npm install -g @bundle-analyzer/cli
  - npm install

script:
  - npm run build
  - npm test

after_script:
  - npm run check
  - npm run cover
  - bash <(curl -s https://codecov.io/bash)
  - webpack --mode production --json | bundle-analyzer --token ${BUNDLE_ANALYZER_TOKEN}
  - cat webpack-stats.json | bundle-analyzer --token ${BUNDLE_ANALYZER_TOKEN}


notifications:
  email: false
